#ifndef TENSORFLOW_LITE_MICRO_EXAMPLES_MICRO_SPEECH_MICRO_FEATURES_SBCNN_MODEL_H_
#define TENSORFLOW_LITE_MICRO_EXAMPLES_MICRO_SPEECH_MICRO_FEATURES_SBCNN_MODEL_H_

extern const unsigned char g_model[];
extern const unsigned int g_model_len;

#endif 